import { PipelineStage, ModelMetric } from "./types";

export const PIPELINE_STAGES: PipelineStage[] = [
  {
    id: "building",
    title: "Building",
    subtitle: "Data Ingestion & Cleaner",
    state: "done",
    progress: 100,
    tasks: [
      "Scrape listings from 12 sources",
      "Deduplicate 48,210 records",
      "Impute missing values (KNN)",
      "Outlier removal (IQR)",
    ],
    badge: { label: "Completed", tone: "green" },
  },
  {
    id: "validating",
    title: "Validating",
    subtitle: "Hyperparameter Tuning & Time-Based Split",
    state: "done",
    progress: 100,
    tasks: [
      "Time-based train/test split (80/20)",
      "Bayesian optimization (200 trials)",
      "5-fold cross-validation",
      "Early stopping at 340 rounds",
    ],
    badge: { label: "Completed", tone: "green" },
  },
  {
    id: "review",
    title: "In Review",
    subtitle: "Model Ensembler & Auditor",
    state: "active",
    progress: 65,
    tasks: [
      "Weighted ensemble (Cat/LGB/XGB)",
      "SHAP feature audit",
      "Fairness check across zones",
      "Drift report generation",
    ],
    badge: { label: "In Progress", tone: "yellow" },
  },
  {
    id: "ready",
    title: "Ready",
    subtitle: "API Deployment",
    state: "queued",
    progress: 0,
    tasks: [
      "Containerize inference service",
      "Blue-green deploy to staging",
      "Smoke test 500 requests",
      "Promote to production",
    ],
    badge: { label: "Queued", tone: "gray" },
  },
];

export const MODEL_METRICS: ModelMetric[] = [
  {
    name: "CatBoost",
    shortName: "CatBoost",
    color: "#f97316",
    rmse: 285000,
    mae: 198000,
    r2: 0.912,
    mape: 8.4,
    inferenceMs: 12,
    weight: 40,
    strengths: ["Categorical handling", "Robust to overfitting", "No manual encoding"],
  },
  {
    name: "LightGBM",
    shortName: "LightGBM",
    color: "#22c55e",
    rmse: 301000,
    mae: 210000,
    r2: 0.901,
    mape: 9.1,
    inferenceMs: 8,
    weight: 30,
    strengths: ["Fastest training", "Memory efficient", "Leaf-wise growth"],
  },
  {
    name: "XGBoost",
    shortName: "XGBoost",
    color: "#3b82f6",
    rmse: 295000,
    mae: 205000,
    r2: 0.906,
    mape: 8.8,
    inferenceMs: 15,
    weight: 30,
    strengths: ["Mature ecosystem", "GPU acceleration", "Regularization built-in"],
  },
];
