/** Thai labels for the model's feature names — mirrors FEATURE_LABELS in ml/api.py. */
export const FEATURE_LABELS: Record<string, string> = {
  comp_ppsqm: "ราคาทรัพย์ขนาดเดียวกันในอดีต",
  comp2_ppsqm: "ราคาทรัพย์ขนาดเดียวกัน",
  comp_gap: "ส่วนต่างจากค่ากลางของเขต",
  comp_n: "จำนวนทรัพย์เทียบเคียง",
  comp2_n: "จำนวนทรัพย์ขนาดเดียวกัน",
  comp_age: "อายุของข้อมูลเทียบเคียง",
  nn_ppsqm: "ราคาทรัพย์ขนาดใกล้เคียงที่สุด",
  nn_dist: "ความต่างของขนาดกับทรัพย์เทียบเคียง",
  band_ppsqm: "ราคาต่อ ตร.ม. ของช่วงขนาดเดียวกัน",
  band_n: "จำนวนข้อมูลในช่วงขนาด",
  dt_ppsqm: "ราคาต่อ ตร.ม. ของเขต ตามประเภททรัพย์",
  dt_n: "จำนวนข้อมูลของเขต",
  dt_iqr: "การกระจายราคาในเขต",
  district_ppsqm: "ราคาต่อ ตร.ม. ของเขต",
  province_ppsqm: "ราคาต่อ ตร.ม. ของจังหวัด",
  prov_type_ppsqm: "ราคาต่อ ตร.ม. ของจังหวัด ตามประเภททรัพย์",
  type_ppsqm: "ราคาต่อ ตร.ม. ตามประเภททรัพย์",
  area_sqm: "พื้นที่ใช้สอย",
  log_area: "พื้นที่ใช้สอย (log)",
  area_per_unit: "พื้นที่ต่อหน่วย",
  n_units: "จำนวนหน่วย",
  district: "เขต / อำเภอ",
  province: "จังหวัด",
  collateral_type: "ประเภททรัพย์",
  year: "ปีที่ประเมิน",
};
